# Generated by Django 5.0 on 2024-08-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Question_id', models.CharField(max_length=256)),
                ('File_path', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Question_id', models.CharField(max_length=256)),
                ('Content', models.CharField(default='none', max_length=256)),
                ('Correction', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Quizz_id', models.CharField(max_length=256)),
                ('Content', models.CharField(default='none', max_length=256)),
                ('Scoring', models.CharField(default='1', max_length=256)),
                ('Order', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Owner_id', models.CharField(max_length=256)),
                ('Title', models.CharField(max_length=256)),
                ('Settings', models.JSONField()),
            ],
        ),
    ]
