# Generated by Django 5.0 on 2024-08-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='Quizz_id',
            field=models.CharField(default='non', max_length=256),
            preserve_default=False,
        ),
    ]
