# Generated by Django 5.0 on 2024-09-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzy_app', '0002_choice_quizz_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Owner_id', models.CharField(max_length=256)),
                ('Subscription_type', models.CharField(max_length=256)),
                ('Subscription_id', models.CharField(max_length=256)),
                ('Creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
